package generator

import (
	"bytes"
	"fmt"
	"text/template"

	"github.com/itrowa/clash-unchained/internal/config"
	"github.com/itrowa/clash-unchained/internal/domains"
)

type TemplateData struct {
	Nodes              []NodeData
	ProxyGroups        []ProxyGroupData
	AIDomains          []string
	HasTailscaleBypass bool
}

type NodeData struct {
	Name     string
	Type     string
	Server   string
	Port     int
	Username string
	Password string
}

type ProxyGroupData struct {
	Name    string
	Type    string
	Proxies []string
}

func Generate(cfg *config.Config) (string, error) {
	data := TemplateData{}

	for _, node := range cfg.Nodes {
		data.Nodes = append(data.Nodes, NodeData{
			Name:     node.Name,
			Type:     node.Type,
			Server:   node.Server,
			Port:     node.Port,
			Username: node.Username,
			Password: node.Password,
		})
	}

	for _, pg := range cfg.ProxyGroups {
		data.ProxyGroups = append(data.ProxyGroups, ProxyGroupData{
			Name:    pg.Name,
			Type:    pg.Type,
			Proxies: pg.Proxies,
		})
	}

	data.HasTailscaleBypass = cfg.Tailscale.Enable

	if cfg.AIDomains.UseBuiltin {
		rules, err := domains.Load()
		if err != nil {
			return "", fmt.Errorf("failed to load AI domains: %w", err)
		}
		data.AIDomains = rules
	}
	data.AIDomains = append(data.AIDomains, cfg.AIDomains.Custom...)

	if len(data.AIDomains) == 0 {
		return "", fmt.Errorf("no AI domains configured")
	}

	for i := range data.AIDomains {
		data.AIDomains[i] = fmt.Sprintf("DOMAIN-SUFFIX,%s,%s", data.AIDomains[i], cfg.AIDomains.ProxyGroup)
	}

	tmpl, err := template.New("global-script.js").Parse(globalScriptTemplate)
	if err != nil {
		return "", fmt.Errorf("failed to parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("failed to execute template: %w", err)
	}

	return buf.String(), nil
}

const globalScriptTemplate = `/**
 * Global Extension Script — Generated by clash-unchained
 *
 * 功能：
 *   - 注入住宅静态节点 + LLM 路由组 + AI 域名规则
 *   - Tailscale 绕过（规则 + DNS）
 *   - 自动检测订阅主代理组
 *   - 幂等保护（多次执行不重复注入）
 *
 * 安装：Clash Verge → 设置 → 扩展 → 全局扩展脚本 → 粘贴保存
 * 适用：任意订阅，新增订阅无需额外配置
 */

function main(config, profileName) {
  // ===========================================================
  // 0. 幂等保护
  // ===========================================================
{{- if .Nodes}}
  if ((config.proxies || []).some(p => p.name === '{{(index .Nodes 0).Name}}')) {
    return config;
  }
{{- end}}

  // ===========================================================
  // 1. 自动检测订阅的主代理组
  // ===========================================================
  // 遍历订阅的 proxy-groups，找第一个不属于我们的 AI 组的 select 组
  var aiGroupNames = [{{range $i, $pg := .ProxyGroups}}{{if $i}}, {{end}}"{{$pg.Name}}"{{end}}];
  var mainGroup = (config['proxy-groups'] || []).find(function(g) {
    return g.type === 'select' && aiGroupNames.indexOf(g.name) === -1;
  });
  var dialer = mainGroup ? mainGroup.name : null;

  // ===========================================================
  // 2. 注入住宅节点
  // ===========================================================
  var nodesToInject = [
{{- range $i, $node := .Nodes}}
{{- if $i}},
{{end}}    {
      name: "{{$node.Name}}",
      type: "{{$node.Type}}",
      server: "{{$node.Server}}",
      port: {{$node.Port}},
{{- if $node.Username}}
      username: "{{$node.Username}}",
{{- end}}
{{- if $node.Password}}
      password: "{{$node.Password}}",
{{- end}}
      "skip-cert-verify": false,
      udp: true
    }
{{- end}}
  ];

  // 绑定 dialer-proxy（自动检测到的订阅主代理组）
  if (dialer) {
    nodesToInject[0]["dialer-proxy"] = dialer;
  }

  config.proxies = [...nodesToInject, ...(config.proxies || [])];

  // ===========================================================
  // 3. 注入代理组
  // ===========================================================
{{- if .ProxyGroups}}
  var groupsToInject = [
{{- range $i, $pg := .ProxyGroups}}
{{- if $i}},
{{end}}    {
      name: "{{$pg.Name}}",
      type: "{{$pg.Type}}",
      proxies: [{{range $j, $p := $pg.Proxies}}{{if $j}}, {{end}}"{{$p}}"{{end}}]
    }
{{- end}}
  ];
  config['proxy-groups'] = [...groupsToInject, ...(config['proxy-groups'] || [])];
{{- end}}

  // ===========================================================
  // 4. AI 域名规则
  // ===========================================================
  var aiServiceRules = [
{{range $i, $rule := .AIDomains}}{{if $i}},
{{end}}    "{{$rule}}"{{end}}
  ];

  // ===========================================================
  // 5. Tailscale 绕过规则
  // ===========================================================
{{- if .HasTailscaleBypass}}
  var tailscaleRules = [
    "IP-CIDR,100.64.0.0/10,DIRECT,no-resolve",
    "IP-CIDR6,fd7a:115c:a1e0::/64,DIRECT,no-resolve",
    "DOMAIN-SUFFIX,ts.net,DIRECT"
  ];

  // 5a. DNS 配置
  if (!config.dns) config.dns = {};
  config.dns.enable = true;
  if (!config.dns['enhanced-mode']) {
    config.dns['enhanced-mode'] = 'fake-ip';
  }
  config.dns['direct-nameserver-follow-policy'] = true;

  if (!config.dns['fake-ip-filter']) {
    config.dns['fake-ip-filter'] = [];
  }
  if (config.dns['fake-ip-filter'].indexOf('*.ts.net') === -1) {
    config.dns['fake-ip-filter'].push('*.ts.net');
  }
  if (config.dns['fake-ip-filter'].indexOf('+.ts.net') === -1) {
    config.dns['fake-ip-filter'].push('+.ts.net');
  }

  if (!config.dns['nameserver-policy']) {
    config.dns['nameserver-policy'] = {};
  }
  config.dns['nameserver-policy']['+.ts.net'] = '100.100.100.100';

  var tsDns = '100.100.100.100';
  if (!config.dns.nameserver) {
    config.dns.nameserver = [tsDns];
  } else if (config.dns.nameserver.indexOf(tsDns) === -1) {
    config.dns.nameserver = [tsDns].concat(config.dns.nameserver);
  }

  config.rules = [...tailscaleRules, ...aiServiceRules, ...(config.rules || [])];
{{- else}}
  config.rules = [...aiServiceRules, ...(config.rules || [])];
{{- end}}

  return config;
}
`
